### POSTS 
GET http://localhost:3000/api/posts/1
### numbers 
GET http://localhost:3000/api/numbers 
### numbers 
GET http://localhost:3000/api/numbers/gt/5
### numbers 
GET http://localhost:3000/api/numbers/obj-values 
### POSTS 
POST http://localhost:3000/posts

###
GET http://localhost:3000/numbers/gt/10
###
GET http://localhost:3000/numbers/obj-valuessdsds