### POSTS 
GET http://localhost:3000/posts 
### numbers 
GET http://localhost:3000/numbers 
### POSTS 
POST http://localhost:3000/posts

###
GET http://localhost:3000/numbers/gt/10
###
GET http://localhost:3000/numbers/obj-values